name: 'W3C Validator'
description: 'Validate HTML Files'
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/main.sh
      shell: bash
branding:
  icon: 'check-square'
  color: 'blue'
