name: w3c-validator
on:
  push:
    branches: [ master, develop ]
  pull_request:
jobs:
  w3c-validator:
    name: Validates HTML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Validator
        uses: bucherfa/w3c-validator-action@0.0
